const BebidaData = {
    bebidaItems: [
      {
        id: 90,
        discount: 50,
        cover: "./images/bebidas/bebida01.jpg",
        name: "Samurai Chu-Hi (vino)",
        price: 2000,
      },
      {
        id: 91,
        discount: 40,
        cover: "./images/bebidas/bebida02.jpg",
        name: "Nipponia Sake (vino)",
        price: 1300,
      },
      {
        id: 92,
        discount: 40,
        cover: "./images/bebidas/bebida03.jpg",
        name: "Cerveza Tsingtao ",
        price: 1200,
      },
      {
        id: 93,
        discount: 40,
        cover: "./images/bebidas/bebida04.jpg",
        name: "Asahi beer",
        price: 1500,
      },
      {
        id: 94,
        discount: 50,
        cover: "./images/bebidas/bebida05.jpg",
        name: "Jinzu (coctel)",
        price: 1300,
      },
      {
        id: 95,
        discount: 50,
        cover: "./images/bebidas/bebida06.jpg",
        name: "Iichiko Sake (vino)",
        price: 1200,
      },
      {
        id: 96,
        discount: 50,
        cover: "./images/bebidas/bebida07.jpg",
        name: "Sake Choya (vino)",
        price: 1400,
      },
      {
        id: 97,
        discount: 50,
        cover: "./images/bebidas/bebida08.jpg",
        name: "Jumaii sake (vino)",
        price: 1300,
      },
      {
        id: 98,
        discount: 50,
        cover: "./images/bebidas/bebida09.jpg",
        name: "Tempt Cider (Sin alcohol)",
        price: 1200,
      },
      {
        id: 99,
        discount: 50,
        cover: "./images/bebidas/bebida10.jpg",
        name: "Goji Chai (Sin alcohol)",
        price: 1200,
      },
      {
        id: 100,
        discount: 50,
        cover: "./images/bebidas/bebida11.jpg",
        name: "Whisky Yamazaki",
        price: 1200,
      },
      {
        id: 101,
        discount: 50,
        cover: "./images/bebidas/bebida12.jpg",
        name: "Chinesse beer",
        price: 1200,
      },
    ],
  }
  export default BebidaData